refactor dmesg parsing

diff --git a/health b/health
--- a/health
+++ b/health
@@ -18,7 +18,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-version="Health version: 1.3.1 - July 19, 2023"
+version="Health version: 1.3.2 - July 22, 2023"
 
 usage() {
 	cat <<-EOF
@@ -33,7 +33,7 @@ usage() {
 	  -m,	compare mounts to /etc/fstab
 	  -z,	display zombie process count, if any
 	  -r,	display health on remote host
-	  -e,	parse dmesg for alerts, errors, etc. (dmesg v2.23+ required)
+	  -e,	parse dmesg for alerts, errors, etc. (may require sudo)
 	  -v,	display version number and exit
 	  -h,	display this help and exit
 
@@ -45,7 +45,7 @@ usage() {
 health() {
 	printf "%bHostname:%b %s\n" "$blue" "$reset" "$(hostname)"
 	[[ -d "/sys/devices/virtual/dmi/id" ]] && {
-		dir="/sys/devices/virtual/dmi/id"
+		local dir="/sys/devices/virtual/dmi/id"
 		printf "%bServer Info:%b %s, %s\n" "$blue" "$reset" "$(< ${dir}/product_name)" "$(< ${dir}/sys_vendor)"; }
 	printf "%bLinux Version:%b %s\n" "$blue" "$reset" \
 		"$(grep -Po "(?<=PRETTY_NAME=\").*[^\"]" /etc/os-release)"
@@ -91,17 +91,15 @@ get_args() {
 			d) check_df "-Th" ;;
 			i) check_df "-i" ;;
 			s)
-				[[ -n $(find "${dir:-.}" ! -type l -perm -002) ]] && \
-					printf "%bWorld writable files:%b\n%s\n" "$blue" "$reset" \
-						"$(find "${dir:-.}" ! -type l -perm -002)"
-				[[ -n $(find "${dir:-.}" -perm -4000 -o -perm -2000) ]] && \
-					printf "%bFiles with setgids/setuids:%b\n%s\n" "$blue" "$reset" \
-						"$(find "${dir:-.}" -perm -4000 -o -perm -2000)"
+				world_write="$(find "${dir:-.}" ! -type l -perm -002)"
+				[[ -n "$world_write" ]] && printf "%bWorld writable files:%b\n%s\n" "$blue" "$reset" "$world_write"
+				setbits="$(find "${dir:-.}" -perm -4000 -o -perm -2000)"
+				[[ -n "$setbits" ]] && printf "%bFiles with setgids/setuids:%b\n%s\n" "$blue" "$reset" "$setbits"
 			;;
 
 			f)
 				printf "%b10 Largest Files in Directory Tree:%b\n" "$blue" "$reset"
-				find "${dir:-.}" -type f -exec du -Sh {} + | sort -rn | head
+				find "${dir:-.}" -type f -print0 | xargs -0 du -Sh | sort -rn | head
 			;;
 
 			m)
@@ -120,28 +118,25 @@ get_args() {
 			;;
 
 			e)
-				if ! dmesg -V &> /dev/null; then
-					printf "health: dmesg version insufficient"
-					printf "Try 'health -h' for more information.\n"; exit 1
-				else
-					if [[ -n $(dmesg -l emerg,crit,alert,err,warn 2> /dev/null) ]]; then
-						[[ -n $(dmesg -l emerg) ]] && \
-							printf "%bemergency messages%b: %d\n" "$red" "$reset" \
-								"$(dmesg -l emerg | wc -l)"
-						[[ -n $(dmesg -l crit) ]] && \
-							printf "%bcritical messages%b: %d\n" "$red" "$reset" \
-								"$(dmesg -l crit | wc -l)"
-						[[ -n $(dmesg -l alert) ]] && \
-							printf "%balert messages%b: %d\n" "$yellow" "$reset" \
-								"$(dmesg -l alert | wc -l)"
-						[[ -n $(dmesg -l err) ]] && \
-							printf "%berror messages%b: %d\n" "$yellow" "$reset" \
-								"$(dmesg -l err | wc -l)"
-						[[ -n $(dmesg -l warn) ]] && \
-							printf "%bwarning messages%b: %d\n" "$yellow" "$reset" \
-								"$(dmesg -l warn | wc -l)"
-					fi
-				fi
+				dmesg -V &> /dev/null || {
+					printf "health: dmesg version/permissions insufficient"
+					printf "Try 'health -h' for more information.\n"; exit 1; }
+				
+				local dmesg=(emerg crit alert err warn)
+				for level in "${dmesg[@]}"; do
+					readarray "${level}" < <(dmesg -l "$level")
+				done
+
+				[[ -n "$emerg" ]] && \
+					printf "%bemergency messages%b: %d\n" "$red" "$reset" "${#emerg[@]}"
+				[[ -n "$crit" ]] && \
+					printf "%bcritical messages%b: %d\n" "$red" "$reset" "${#crit[@]}"
+				[[ -n "$alert" ]] && \
+					printf "%balert messages%b: %d\n" "$yellow" "$reset" "${#alert[@]}"
+				[[ -n "$err" ]] && \
+					printf "%berror messages%b: %d\n" "$yellow" "$reset" "${#err[@]}"
+				[[ -n "$warn" ]] && \
+					printf "%bwarning messages%b: %d\n" "$yellow" "$reset" "${#warn[@]}"
 			;;
 
 			?)
