add check for no matching directory; improve readability

diff --git a/health b/health
--- a/health
+++ b/health
@@ -18,7 +18,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-version="Health version: 1.2.7 - June 25, 2023"
+version="Health version: 1.2.8 - June 25, 2023"
 
 usage() {
 	cat <<-EOF
@@ -46,15 +46,20 @@ health() {
 	printf "%bHostname:%b %s\n" "$blue" "$reset" "$(hostname)"
 	printf "%bServer Info:%b %s, %s\n" "$blue" "$reset" \
 		"$(< /sys/devices/virtual/dmi/id/product_name)" "$(< /sys/devices/virtual/dmi/id/sys_vendor)"
-	printf "%bRHEL Version:%b %s\n" "$blue" "$reset" "$(< /etc/redhat-release)"
+	printf "%bLinux Version:%b %s\n" "$blue" "$reset" \
+		"$(grep -Po "(?<=PRETTY_NAME=\").*[^\"]" /etc/os-release)"
 	printf "%bKernel Version:%b %s\n" "$blue" "$reset" "$(uname -r)"
 	printf "%bUptime:%b %s\n" "$blue" "$reset" "$(uptime)"
 	printf "%bUsers Currently Logged in:%b\n%s\n" "$blue" "$reset" "$(who -u)"
 	printf "%bMemory Usage:%b\n%s\n" "$blue" "$reset" "$(free -h)"
-	printf "%bTop 5 Processes by Memory:%b\n%s\n" "$blue" "$reset" "$(ps -eo %mem,comm,pid --sort=-%mem | head -n 6)"
-	printf "%bTop 5 Processes by CPU:%b\n%s\n" "$blue" "$reset" "$(ps -eo pcpu,comm,pid --sort=-pcpu | head -n 6)"
+	printf "%bTop 5 Processes by Memory:%b\n%s\n" "$blue" "$reset" \
+		"$(ps -eo %mem,comm,pid --sort=-%mem | head -n 6)"
+	printf "%bTop 5 Processes by CPU:%b\n%s\n" "$blue" "$reset" \
+		"$(ps -eo pcpu,comm,pid --sort=-pcpu | head -n 6)"
 	printf "%bMounts:%b\n" "$blue" "$reset"
-	if ! timeout 2 df &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
+	if ! timeout 2 df &> /dev/null; then
+		printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return
+	fi
 	while IFS= read -r mount; do
 		if ! findmnt "$mount" &> /dev/null; then
 			printf "%b%s is declared in fstab but not mounted\n%b" "$yellow" "$mount" "$reset"
@@ -74,7 +79,9 @@ get_args() {
 			r) ssh -qt "$OPTARG" "/usr/bin/health" ;;
 			u) find "${dir:-.}" -type f -printf "%h\n" | cut -d/ -f-2 | sort | uniq -c | sort -nr ;;
 			d)
-				if ! timeout 2 df &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
+				if ! timeout 2 df &> /dev/null; then
+					printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return
+				fi
 				printf "%bDisk Space Usage:%b\n" "$blue" "$reset"
 				while IFS= read -r line; do
 					case "$line" in
@@ -86,7 +93,9 @@ get_args() {
 			;;
 
 			i)
-				if ! timeout 2 df &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
+				if ! timeout 2 df &> /dev/null; then
+					printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return
+				fi
 				printf "%bInode Usage:%b\n" "$blue" "$reset"
 				while IFS= read -r line; do
 					case "$line" in
@@ -99,9 +108,11 @@ get_args() {
 
 			s)
 				[[ -n $(find "${dir:-.}" ! -type l -perm -002) ]] && \
-					printf "%bWorld writable files:%b\n%s\n" "$blue" "$reset" "$(find "${dir:-.}" ! -type l -perm -002)"
+					printf "%bWorld writable files:%b\n%s\n" "$blue" "$reset" \
+						"$(find "${dir:-.}" ! -type l -perm -002)"
 				[[ -n $(find "${dir:-.}" -perm -4000 -o -perm -2000) ]] && \
-					printf "%bFiles with setgids/setuids:%b\n%s\n" "$blue" "$reset" "$(find "${dir:-.}" -perm -4000 -o -perm -2000)"
+					printf "%bFiles with setgids/setuids:%b\n%s\n" "$blue" "$reset" \
+						"$(find "${dir:-.}" -perm -4000 -o -perm -2000)"
 			;;
 
 			f)
@@ -131,15 +142,20 @@ get_args() {
 				else
 					if [[ -n $(dmesg -l emerg,crit,alert,err,warn 2> /dev/null) ]]; then
 						[[ -n $(dmesg -l emerg) ]] && \
-							printf "%bemergency messages%b: %d\n" "$red" "$reset" "$(dmesg -l emerg | wc -l)"
+							printf "%bemergency messages%b: %d\n" "$red" "$reset" \
+								"$(dmesg -l emerg | wc -l)"
 						[[ -n $(dmesg -l crit) ]] && \
-							printf "%bcritical messages%b: %d\n" "$red" "$reset" "$(dmesg -l crit | wc -l)"
+							printf "%bcritical messages%b: %d\n" "$red" "$reset" \
+								"$(dmesg -l crit | wc -l)"
 						[[ -n $(dmesg -l alert) ]] && \
-							printf "%balert messages%b: %d\n" "$orange" "$reset" "$(dmesg -l alert | wc -l)"
+							printf "%balert messages%b: %d\n" "$orange" "$reset" \
+								"$(dmesg -l alert | wc -l)"
 						[[ -n $(dmesg -l err) ]] && \
-							printf "%berror messages%b: %d\n" "$yellow" "$reset" "$(dmesg -l err | wc -l)"
+							printf "%berror messages%b: %d\n" "$yellow" "$reset" \
+								"$(dmesg -l err | wc -l)"
 						[[ -n $(dmesg -l warn) ]] && \
-							printf "%bwarning messages%b: %d\n" "$yellow" "$reset" "$(dmesg -l warn | wc -l)"
+							printf "%bwarning messages%b: %d\n" "$yellow" "$reset" \
+								"$(dmesg -l warn | wc -l)"
 					fi
 				fi
 			;;
@@ -150,6 +166,8 @@ get_args() {
 			;;
 		esac
 	done
+	shift "$((OPTIND -1))"
+	[[ -n "${1:-}" ]] && printf "health: %s: Not a directory\n" "$1"
 }
 
 main() {
