update tabbing

diff --git a/health b/health
--- a/health
+++ b/health
@@ -26,7 +26,7 @@ usage() {
 
 	  -d,   display colorized file system disk space usage
 	  -i,   display colorized file systems inodes usage
-	  -s,   perform common file system STIG checks
+	  -s,   search for common file permission vulnerabilities
 	  -f,   report 10 largest files in directory tree
 	  -m,   compare mounts to /etc/fstab
 	  -z,   display zombie process count, if any
@@ -42,119 +42,119 @@ usage() {
 }
 
 health() {
-        printf "%bHostname:%b " "$blue" "$reset"; hostname -f
-        printf "%bServer Type:%b %s, %s\n" "$blue" "$reset"\
-                "$(< /sys/devices/virtual/dmi/id/product_name)" "$(< /sys/devices/virtual/dmi/id/sys_vendor)"
-        printf "%bRHEL Version:%b %s\n" "$blue" "$reset" "$(< /etc/redhat-release)"
-        printf "%bKernel Version:%b " "$blue" "$reset"; uname -r
-        printf "%bUptime:%b " "$blue" "$reset"; uptime
-        printf "%bUsers Currently Logged in:%b\n" "$blue" "$reset"; who -u
-        printf "%bMemory Usage:%b\n" "$blue" "$reset"; free -h
-        printf "%bTop 5 Memory Comsuming Processes:%b\n" "$blue" "$reset"; ps -eo %mem,%cpu,comm --sort=-%mem | head -n 6
-        printf "%bFile System Report:%b\n" "$blue" "$reset"
-        if ! timeout 1 df -h &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
-        [[ -n $(df -h | grep "100%") ]] && printf "%bFull file system:\n%b" "$blue" "$reset"; df -h | grep "100%" && error=true
-        [[ -n $(df -i | grep "100%") ]] && printf "%bFull inodes:\n%b" "$blue" "$reset"; df -i | grep "100%" && error=true
-        [[ -z "$error" ]] && printf "Mounts & disk/inode usage: %bGOOD%b\n" "$green" "$reset"
+	printf "%bHostname:%b " "$blue" "$reset"; hostname -f
+	printf "%bServer Type:%b %s, %s\n" "$blue" "$reset"\
+		"$(< /sys/devices/virtual/dmi/id/product_name)" "$(< /sys/devices/virtual/dmi/id/sys_vendor)"
+	printf "%bRHEL Version:%b %s\n" "$blue" "$reset" "$(< /etc/redhat-release)"
+	printf "%bKernel Version:%b " "$blue" "$reset"; uname -r
+	printf "%bUptime:%b " "$blue" "$reset"; uptime
+	printf "%bUsers Currently Logged in:%b\n" "$blue" "$reset"; who -u
+	printf "%bMemory Usage:%b\n" "$blue" "$reset"; free -h
+	printf "%bTop 5 Memory Comsuming Processes:%b\n" "$blue" "$reset"; ps -eo %mem,%cpu,comm --sort=-%mem | head -n 6
+	printf "%bFile System Report:%b\n" "$blue" "$reset"
+	if ! timeout 1 df -h &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
+	[[ -n $(df -h | grep "100%") ]] && printf "%bFull file system:\n%b" "$blue" "$reset"; df -h | grep "100%" && error=true
+	[[ -n $(df -i | grep "100%") ]] && printf "%bFull inodes:\n%b" "$blue" "$reset"; df -i | grep "100%" && error=true
+	[[ -z "$error" ]] && printf "Mounts & disk/inode usage: %bGOOD%b\n" "$green" "$reset"
 }
 
 get_args() {
-        while getopts ':hvr:dislfmze' option; do
-                case "$option" in
-                        h) usage; exit 0 ;;
-                        v) printf "%s\n" "$version"; exit 0 ;;
-                        r) ssh -qt "$OPTARG" health ;;
-                        d)
-                                if ! timeout 1 df -h &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
-                                printf "%bDisk Space Usage:%b\n" "$blue" "$reset"
-                                while IFS="" read -r line; do
-                                        case "$line" in
-                                                *100%*) printf "%b%s%b\n" "$red" "$line" "$reset" ;;
-                                                *9?%*) printf "%b%s%b\n" "$yellow" "$line" "$reset" ;;
-                                                *) printf "%s\n" "$line" ;;
-                                        esac
-                                done < <(if ! df -Th "$dir" 2> /dev/null; then df -Th; fi)
-                        ;;
+	while getopts ':hvr:dislfmze' option; do
+		case "$option" in
+			h) usage; exit 0 ;;
+			v) printf "%s\n" "$version"; exit 0 ;;
+			r) ssh -qt "$OPTARG" health ;;
+			d)
+				if ! timeout 1 df -h &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
+				printf "%bDisk Space Usage:%b\n" "$blue" "$reset"
+				while IFS="" read -r line; do
+					case "$line" in
+						*100%*) printf "%b%s%b\n" "$red" "$line" "$reset" ;;
+						*9?%*) printf "%b%s%b\n" "$yellow" "$line" "$reset" ;;
+						*) printf "%s\n" "$line" ;;
+					esac
+				done < <(if ! df -Th "$dir" 2> /dev/null; then df -Th; fi)
+			;;
 
-                        i)
-                                if ! timeout 1 df -h &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
-                                printf "%bInode Usage:%b\n" "$blue" "$reset"
-                                while IFS="" read -r line; do
-                                        case "$line" in
-                                                *100%*) printf "%b%s%b\n" "$red" "$line" "$reset" ;;
-                                                *9?%*) printf "%b%s%b\n" "$yellow" "$line" "$reset" ;;
-                                                *) printf "%s\n" "$line" ;;
-                                        esac
-                                done < <(if ! df -i "$dir" 2> /dev/null; then df -i; fi)
-                        ;;
+			i)
+				if ! timeout 1 df -h &> /dev/null; then printf "%bHung mount detected.%b\n" "$yellow" "$reset"; return; fi
+				printf "%bInode Usage:%b\n" "$blue" "$reset"
+				while IFS="" read -r line; do
+					case "$line" in
+						*100%*) printf "%b%s%b\n" "$red" "$line" "$reset" ;;
+						*9?%*) printf "%b%s%b\n" "$yellow" "$line" "$reset" ;;
+						*) printf "%s\n" "$line" ;;
+					esac
+				done < <(if ! df -i "$dir" 2> /dev/null; then df -i; fi)
+			;;
 
-                        s)
-                                printf "%bWorld writable files:%b\n" "$blue" "$reset"
-                                sudo find "${dir:-.}" ! -type l -perm -002
-                                printf "%bFiles with setuids:%b\n" "$blue" "$reset"
-                                sudo find "${dir:-.}" -perm -4000
-                                printf "%bFiles with setguids:%b\n" "$blue" "$reset"
-                                sudo find "${dir:-.}" -perm -2000
-                        ;;
+			s)
+				printf "%bWorld writable files:%b\n" "$blue" "$reset"
+				sudo find "${dir:-.}" ! -type l -perm -002
+				printf "%bFiles with setuids:%b\n" "$blue" "$reset"
+				sudo find "${dir:-.}" -perm -4000
+				printf "%bFiles with setguids:%b\n" "$blue" "$reset"
+				sudo find "${dir:-.}" -perm -2000
+			;;
 
-                        f)
-                                printf "%b10 Largest Files in Directory Tree:%b\n" "$blue" "$reset"
-                                sudo find "${dir:-.}" -type f -exec du -Sh {} + | sort -rn | head
-                        ;;
+			f)
+				printf "%b10 Largest Files in Directory Tree:%b\n" "$blue" "$reset"
+				sudo find "${dir:-.}" -type f -exec du -Sh {} + | sort -rn | head
+			;;
 
-                        m)
-                                while IFS="" read -r mount; do
-                                        if ! findmnt "$mount" &> /dev/null; then
-                                                printf "%b%s is declared in fstab but not mounted\n%b" "$red" "$mount" "$reset"
-                                        else
-                                                printf "%s is mounted properly\n" "$mount"
-                                        fi
-                                done < <(awk '$1!~/^#/ && $2~/^[/]/{print $2}' /etc/fstab)
-                        ;;
+			m)
+				while IFS="" read -r mount; do
+					if ! findmnt "$mount" &> /dev/null; then
+						printf "%b%s is declared in fstab but not mounted\n%b" "$red" "$mount" "$reset"
+					else
+						printf "%s is mounted properly\n" "$mount"
+					fi
+				done < <(awk '$1!~/^#/ && $2~/^[/]/{print $2}' /etc/fstab)
+			;;
 
-                        z)
-                                printf "%bZombie Process Count: %b" "$blue" "$reset"
-                                ps axo stat | awk 'BEGIN{i=0}/Z/{i++;}END{print i}'
-                        ;;
+			z)
+				printf "%bZombie Process Count: %b" "$blue" "$reset"
+				ps axo stat | awk 'BEGIN{i=0}/Z/{i++;}END{print i}'
+			;;
 
-                        e)
-                                if [[ -n $(dmesg -l emerg,crit,alert,err,warn 2> /dev/null) ]]; then
-                                        printf "%bdmesg:%b\n" "$blue" "$reset"
-                                        [[ -n $(dmesg -l emerg) ]] && \
-                                                printf "%bemergency messages%b: %d\n" "$red" "$reset" "$(dmesg -l emerg | wc -l)"
-                                        [[ -n $(dmesg -l alert) ]] && \
-                                                printf "%balert messages%b: %d\n" "$red" "$reset" "$(dmesg -l alert | wc -l)"
-                                        [[ -n $(dmesg -l crit) ]] && \
-                                                printf "%bcritical messages%b: %d\n" "$orange" "$reset" "$(dmesg -l crit | wc -l)"
-                                        [[ -n $(dmesg -l err) ]] && \
-                                                printf "%berror messages%b: %d\n" "$yellow" "$reset" "$(dmesg -l err | wc -l)"
-                                        [[ -n $(dmesg -l warn) ]] && \
-                                                printf "%bwarning messages%b: %d\n" "$yellow" "$reset" "$(dmesg -l warn | wc -l)"
-                                fi
-                        ;;
+			e)
+				if [[ -n $(dmesg -l emerg,crit,alert,err,warn 2> /dev/null) ]]; then
+					printf "%bdmesg:%b\n" "$blue" "$reset"
+					[[ -n $(dmesg -l emerg) ]] && \
+						printf "%bemergency messages%b: %d\n" "$red" "$reset" "$(dmesg -l emerg | wc -l)"
+					[[ -n $(dmesg -l alert) ]] && \
+						printf "%balert messages%b: %d\n" "$red" "$reset" "$(dmesg -l alert | wc -l)"
+					[[ -n $(dmesg -l crit) ]] && \
+						printf "%bcritical messages%b: %d\n" "$orange" "$reset" "$(dmesg -l crit | wc -l)"
+					[[ -n $(dmesg -l err) ]] && \
+						printf "%berror messages%b: %d\n" "$yellow" "$reset" "$(dmesg -l err | wc -l)"
+					[[ -n $(dmesg -l warn) ]] && \
+						printf "%bwarning messages%b: %d\n" "$yellow" "$reset" "$(dmesg -l warn | wc -l)"
+				fi
+			;;
 
-                        ?)
-                                printf "health: invalid option -- '%s'\n" "$OPTARG"
-                                printf "Try 'health -h' for more information.\n"; exit 1
-                        ;;
-                esac
-        done
+			?)
+				printf "health: invalid option -- '%s'\n" "$OPTARG"
+				printf "Try 'health -h' for more information.\n"; exit 1
+			;;
+		esac
+	done
 }
 
 main() {
-        green='\033[38;5;119m'
-        yellow='\033[38;5;226m'
-        blue='\033[38;5;33m'
-        red='\033[38;5;160m'
-        orange='\033[38;5;202m'
-        reset='\033[0m'
-        if [[ "$#" -ge 1 ]]; then
-                for dir in "$@"; do :; done
-                [[ ! -d "$dir" ]] && unset dir
-                get_args "$@"
-        else
-                health
-        fi
+	green='\033[38;5;119m'
+	yellow='\033[38;5;226m'
+	blue='\033[38;5;33m'
+	red='\033[38;5;160m'
+	orange='\033[38;5;202m'
+	reset='\033[0m'
+	if [[ "$#" -ge 1 ]]; then
+		for dir in "$@"; do :; done
+		[[ ! -d "$dir" ]] && unset dir
+		get_args "$@"
+	else
+		health
+	fi
 }
 
 main "$@"
