various updates

diff --git a/health b/health
--- a/health
+++ b/health
@@ -18,7 +18,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-readonly version="Health version: 1.6.4 - January 25, 2024"
+readonly version="Health version: 1.6.5 - January 27, 2024"
 
 usage() {
     printf "Usage: health [OPTION]... [DIRECTORY]...\n"
@@ -29,7 +29,7 @@ usage() {
     printf "  -h,   display this help and exit\n"
     printf "  -i,   display colorized file systems inodes usage\n"
     printf "  -k,   display kernel information; check for updates\n"
-    printf "  -m,   compare mounts to /etc/fstab\n"
+    printf "  -m,   check mounts for common errors\n"
     printf "  -n,   display basic network details\n"
     printf "  -r,   display health on remote host\n"
     printf "  -s,   search for common file permission vulnerabilities\n"
@@ -40,7 +40,6 @@ usage() {
 }
 
 health() {
-    local mount error
     printf "%bHostname:%b %s\n" "$blue" "$reset" "$(hostname)"
     get_network_info
     if [[ -f /sys/devices/virtual/dmi/id/product_name && -f /sys/devices/virtual/dmi/id/sys_vendor ]]; then
@@ -56,16 +55,7 @@ health() {
         "$(ps -eo %mem,comm,pid --sort=-%mem | head -n 6)"
     printf "%bTop 5 Processes by CPU:%b\n%s\n" "$blue" "$reset" \
         "$(ps -eo pcpu,comm,pid --sort=-pcpu | head -n 6)"
-    printf "%bMounts:%b\n" "$blue" "$reset"
-    timeout 2 df &> /dev/null || { printf "%bHung mount detected.%b\n" "$yellow" "$reset" >&2; return 1; }
-    while read -r mount; do
-        findmnt "$mount" &> /dev/null || {
-            printf "%b%s is declared in fstab but not mounted\n%b" "$yellow" "$mount" "$reset"
-            error=true; }
-    done < <(awk '!/^#/ && $2~/^[/]/ {print $2}' /etc/fstab)
-    [[ -z "$error" ]] && printf "No issues detected\n"
-    printf "%bFull File Systems:%b\n%s\n" "$blue" "$reset" "$(df -h | grep "100%" || printf "None\n")"
-    printf "%bFull Inodes:%b\n%s\n" "$blue" "$reset" "$(df -i | grep "100%" || printf "None\n")"
+    check_mounts
 }
 
 check_df() {
@@ -127,53 +117,46 @@ check_kernel() {
             printf "  Available (yum update): \t%s\n" "$available_kernel"
         fi
     fi
-
     printf "  Current running kernel: \t%s\n" "$current_kernel"
 }
 
 check_mounts() {
-    local mount
+    local mount error
+    printf "%bMounts:%b\n" "$blue" "$reset"
+    timeout 2 df &> /dev/null || { printf "%bHung mount detected.%b\n" "$yellow" "$reset" >&2; return 1; }
     while read -r mount; do
-        if findmnt "$mount" &> /dev/null; then
-            printf "%s is mounted properly\n" "$mount"
-        else
-            printf "%b%s is declared in fstab but not mounted\n%b" "$red" "$mount" "$reset" >&2
-        fi
-    done < <(awk '!/^#/ && $2~/^[/]/{print $2}' /etc/fstab)
+        findmnt "$mount" &> /dev/null || {
+            printf "%b%s is declared in fstab but not mounted\n%b" "$yellow" "$mount" "$reset"
+            error=true; }
+    done < <(awk '!/^#/ && $2~/^[/]/ {print $2}' /etc/fstab)
+    [[ -z "$error" ]] && printf "No issues detected\n"
+    printf "%bFull File Systems:%b\n%s\n" "$blue" "$reset" "$(df -h | grep "100%" || printf "None\n")"
+    printf "%bFull Inodes:%b\n%s\n" "$blue" "$reset" "$(df -i | grep "100%" || printf "None\n")"
 }
 
 get_network_info() {
-    local network_info gateway interface ip
-    network_info=$(ip route 2>/dev/null)
-    if [[ -n "$network_info" ]]; then
-        printf "%bNetwork Info:%b\n" "$blue" "$reset"
-        printf "  Interface(s):\n"
-        while read -r interface ip; do
-            printf "\t%s - %s\n" "$interface" "$ip"
-        done < <(echo "$network_info" | awk '/src/{print $3, $9}')
-        gateway=$(echo "$network_info" | awk '/default/{print $3}')
-        if [[ -n "$gateway" ]]; then
-            printf "  Default gateway(s):\n"
-            while read -r gateway; do
-                if ping -c 1 "$gateway" &> /dev/null; then
-                    printf "\t%s (%breachable%b)\n" "$gateway" "$green" "$reset"
-                else
-                    printf "\t%s (%bunreachable%b)\n" "$gateway" "$yellow" "$reset"
-                fi
-            done <<< "$gateway"
+    local interface ip gateway dns
+    printf "%bNetwork Info:%b\n" "$blue" "$reset"
+    printf "  Interface(s):\n"
+    while read -r interface ip; do
+        printf "\t%s - %s\n" "$interface" "$ip"
+    done < <(ip route 2> /dev/null | awk '/src/{print $3, $9}')
+    printf "  Default gateway(s):\n"
+    while read -r gateway; do
+        if ping -W1 -c1 "$gateway" &> /dev/null; then
+            printf "\t%s (%breachable%b)\n" "$gateway" "$green" "$reset"
+        else
+            printf "\t%s (%bunreachable%b)\n" "$gateway" "$yellow" "$reset"
         fi
-    fi
-    dns_info=$(awk '/^nameserver/{print $2}' /etc/resolv.conf 2>/dev/null)
-    if [[ -n "$dns_info" ]]; then
-        printf "  DNS nameserver(s):\n"
-        while read -r dns; do
-            if ping -c 1 "$dns" &> /dev/null; then
-                printf "\t%s (%breachable%b)\n" "$dns" "$green" "$reset"
-            else
-                printf "\t%s (%bpotential DNS error%b)\n" "$dns" "$yellow" "$reset"
-            fi
-        done <<< "$dns_info"
-    fi
+    done < <(ip route 2> /dev/null | awk '/default/{print $3}')
+    printf "  DNS nameserver(s):\n"
+    while read -r dns; do
+        if ping -W1 -c1 "$dns" &> /dev/null; then
+            printf "\t%s (%breachable%b)\n" "$dns" "$green" "$reset"
+        else
+            printf "\t%s (%bpotential DNS error%b)\n" "$dns" "$yellow" "$reset"
+        fi
+    done < <(awk '/^nameserver/{print $2}' /etc/resolv.conf 2> /dev/null)
 }
 
 file_vulnerability() {
@@ -192,19 +175,10 @@ zombies() {
 get_args() {
     while getopts ':defhikmnr:suvz' option; do
         case "$option" in
-            d) d=true ;;
-            e) e=true ;;
-            f) f=true ;;
+            d|e|f|i|k|m|n|s|u|z) args_array+=("$option") ;;
             h) usage; exit 0 ;;
-            i) i=true ;;
-            k) k=true ;;
-            m) m=true ;;
-            n) n=true ;;
-            r) ssh -qt "$OPTARG" "bash -s" < "$0"; exit 0 ;;
-            s) s=true ;;
-            u) u=true ;;
+            r) ssh -qt "$OPTARG" "bash -s" < "$0" ;;
             v) printf "%s\n" "$version"; exit 0 ;;
-            z) z=true ;;
             ?)
                 printf "health: invalid option -- '%s'\n" "$OPTARG" >&2
                 printf "Try 'health -h' for more information.\n" >&2; exit 2
@@ -230,22 +204,20 @@ main() {
     red='\033[38;5;160m'
     reset='\033[0m'
 
-    if [[ "$#" -ge 1 ]]; then
-        get_args "$@"
-    else
-        health
-    fi
+    [[ "$#" -eq 0 ]] && { health; exit 0; } || get_args "$@"
 
-    [[ "$d" ]] && check_df "-Th"
-    [[ "$e" ]] && dmesg_parse
-    [[ "$f" ]] && large_files
-    [[ "$i" ]] && check_df "-Ti"
-    [[ "$k" ]] && check_kernel
-    [[ "$m" ]] && check_mounts
-    [[ "$n" ]] && get_network_info
-    [[ "$s" ]] && file_vulnerability
-    [[ "$u" ]] && find "$dir" -xdev -printf '%h\n' | sort | uniq -c | sort -rn | head
-    [[ "$z" ]] && zombies
+    for arg in "${args_array[@]}"; do
+        [[ "$arg" == "d" ]] && check_df "-Th"
+        [[ "$arg" == "e" ]] && dmesg_parse
+        [[ "$arg" == "f" ]] && large_files
+        [[ "$arg" == "i" ]] && check_df "-Ti"
+        [[ "$arg" == "k" ]] && check_kernel
+        [[ "$arg" == "m" ]] && check_mounts
+        [[ "$arg" == "n" ]] && get_network_info
+        [[ "$arg" == "s" ]] && file_vulnerability
+        [[ "$arg" == "u" ]] && find "$dir" -xdev -printf '%h\n' | sort | uniq -c | sort -rn | head
+        [[ "$arg" == "z" ]] && zombies
+    done
 
     return 0
 }
